### ISSUE TITLE
its not letting me start the server?[BUG]

### ISSUE THREAD

**Issue by SilverHammer09** [TinyPandas/SC-Multiplayer-Mod#5]
## Context
Version: the newest one

Environment: (Client or Server) client

## Description
> Describe the issue you are experiencing
- when i got to start the server it says node is not recognized

## Steps to reproduce
> Describe the steps to reproduce the issue describe
1. Step 1 got the start server
2. Step 2 double click

**Comment by TinyPandas** [comment]
You must have the latest version of node.js installed.
